import { COLORS, DEFAULT_GRID_SETTINGS } from './constants'
import {
  cloneGridSettings,
  cloneLayoutMap,
  createLayoutMap,
} from './grid'
import type { GridItem, GridSettingsMap, LayoutMap } from './types'

const uniqueId = () => Number(Date.now() + Math.floor(Math.random() * 1000))

const withItems = (configs: { color: string; layout: LayoutMap }[]) =>
  configs.map(({ color, layout }) => ({
    id: uniqueId(),
    color,
    layout: cloneLayoutMap(layout),
  }))

type TemplateFactory = () => {
  gridSettings: GridSettingsMap
  items: GridItem[]
}

export const TEMPLATE_FACTORIES: Record<string, TemplateFactory> = {
  hero: () => ({
    gridSettings: {
      xs: { cols: 1, rows: 2, gap: 4 },
      sm: { cols: 1, rows: 2, gap: 4 },
      md: { cols: 2, rows: 2, gap: 6 },
      lg: { cols: 2, rows: 2, gap: 6 },
      xl: { cols: 2, rows: 2, gap: 6 },
      '2xl': { cols: 2, rows: 2, gap: 8 },
    },
    items: withItems([
      {
        color: 'bg-blue-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          md: {
            colStart: '1',
            colEnd: '2',
            rowStart: '1',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          lg: {
            colStart: '1',
            colEnd: '2',
            rowStart: '1',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          xl: {
            colStart: '1',
            colEnd: '2',
            rowStart: '1',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          '2xl': {
            colStart: '1',
            colEnd: '2',
            rowStart: '1',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
        },
      },
      {
        color: 'bg-purple-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          md: {
            colStart: '2',
            colEnd: '3',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          lg: {
            colStart: '2',
            colEnd: '3',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          xl: {
            colStart: '2',
            colEnd: '3',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          '2xl': {
            colStart: '2',
            colEnd: '3',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
        },
      },
      {
        color: 'bg-pink-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          md: {
            colStart: '2',
            colEnd: '3',
            rowStart: '2',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          lg: {
            colStart: '2',
            colEnd: '3',
            rowStart: '2',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          xl: {
            colStart: '2',
            colEnd: '3',
            rowStart: '2',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          '2xl': {
            colStart: '2',
            colEnd: '3',
            rowStart: '2',
            rowEnd: '3',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
        },
      },
    ]),
  }),
  sidebar: () => ({
    gridSettings: {
      xs: { cols: 1, rows: 3, gap: 4 },
      sm: { cols: 1, rows: 3, gap: 4 },
      md: { cols: 4, rows: 3, gap: 4 },
      lg: { cols: 4, rows: 3, gap: 6 },
      xl: { cols: 4, rows: 3, gap: 6 },
      '2xl': { cols: 4, rows: 3, gap: 6 },
    },
    items: withItems([
      {
        color: 'bg-indigo-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          md: {
            colStart: '1',
            colEnd: '5',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          lg: {
            colStart: '1',
            colEnd: '5',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          xl: {
            colStart: '1',
            colEnd: '5',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          '2xl': {
            colStart: '1',
            colEnd: '5',
            rowStart: '1',
            rowEnd: '2',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
        },
      },
      {
        color: 'bg-cyan-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          md: {
            colStart: '1',
            colEnd: '2',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          lg: {
            colStart: '1',
            colEnd: '2',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          xl: {
            colStart: '1',
            colEnd: '2',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          '2xl': {
            colStart: '1',
            colEnd: '2',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
        },
      },
      {
        color: 'bg-green-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          md: {
            colStart: '2',
            colEnd: '5',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          lg: {
            colStart: '2',
            colEnd: '5',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          xl: {
            colStart: '2',
            colEnd: '5',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
          '2xl': {
            colStart: '2',
            colEnd: '5',
            rowStart: '2',
            rowEnd: '4',
            colSpan: 1,
            rowSpan: 1,
            order: 'auto',
          },
        },
      },
    ]),
  }),
  cards: () => ({
    gridSettings: {
      xs: { cols: 1, rows: 4, gap: 4 },
      sm: { cols: 2, rows: 4, gap: 4 },
      md: { cols: 3, rows: 4, gap: 4 },
      lg: { cols: 4, rows: 4, gap: 6 },
      xl: { cols: 4, rows: 4, gap: 6 },
      '2xl': { cols: 4, rows: 4, gap: 6 },
    },
    items: Array.from({ length: 8 }).map((_, index) => ({
      id: uniqueId(),
      color: COLORS[index % COLORS.length],
      layout: createLayoutMap(),
    })),
  }),
  masonry: () => ({
    gridSettings: {
      xs: { cols: 2, rows: 6, gap: 4 },
      sm: { cols: 3, rows: 6, gap: 4 },
      md: { cols: 4, rows: 6, gap: 4 },
      lg: { cols: 4, rows: 6, gap: 6 },
      xl: { cols: 4, rows: 6, gap: 6 },
      '2xl': { cols: 4, rows: 6, gap: 6 },
    },
    items: withItems([
      {
        color: 'bg-red-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          md: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          lg: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          xl: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
          '2xl': {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 2,
            order: 'auto',
          },
        },
      },
      {
        color: 'bg-orange-500',
        layout: createLayoutMap(),
      },
      {
        color: 'bg-yellow-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 3,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 3,
            order: 'auto',
          },
          md: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 3,
            order: 'auto',
          },
          lg: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 3,
            order: 'auto',
          },
          xl: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 3,
            order: 'auto',
          },
          '2xl': {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 1,
            rowSpan: 3,
            order: 'auto',
          },
        },
      },
      {
        color: 'bg-green-500',
        layout: createLayoutMap(),
      },
      {
        color: 'bg-teal-500',
        layout: {
          xs: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 2,
            rowSpan: 1,
            order: 'auto',
          },
          sm: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 2,
            rowSpan: 1,
            order: 'auto',
          },
          md: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 2,
            rowSpan: 1,
            order: 'auto',
          },
          lg: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 2,
            rowSpan: 1,
            order: 'auto',
          },
          xl: {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 2,
            rowSpan: 1,
            order: 'auto',
          },
          '2xl': {
            colStart: 'auto',
            colEnd: 'auto',
            rowStart: 'auto',
            rowEnd: 'auto',
            colSpan: 2,
            rowSpan: 1,
            order: 'auto',
          },
        },
      },
      {
        color: 'bg-blue-500',
        layout: createLayoutMap(),
      },
    ]),
  }),
}

export const createEmptyTemplate = (): {
  gridSettings: GridSettingsMap
  items: GridItem[]
} => ({
  gridSettings: cloneGridSettings(DEFAULT_GRID_SETTINGS),
  items: [],
})
